/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id3.ui;

import id3.Arbol;
import id3.Conexion;
import id3.NodoAgregable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Paco
 */
public class PnlPrepareID3 extends javax.swing.JPanel {

    public FrameID3 frame;
    public Connection conexion;
    public String subname;
    public String usuario;
    public String password;
    DefaultListModel lmAtribPred = new DefaultListModel();
    DefaultListModel lmPrepareAtribPred = new DefaultListModel();

    public PnlPrepareID3() {
        initComponents();

    }

    public void prepareLists() {
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SHOW TABLES");
            while (rs.next()) {
                cmbBoxTablas.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PnlPrepareID3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTablaConocimiento = new javax.swing.JLabel();
        cmbBoxTablas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAtributosPredictores = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrepareAtribPred = new javax.swing.JList();
        btnAgregarAtribPred = new javax.swing.JButton();
        btnEliminarAtribPred = new javax.swing.JButton();
        btnAgregarBase = new javax.swing.JButton();
        txtBase = new javax.swing.JTextField();
        btnEliminarBase = new javax.swing.JButton();
        btnCalcularID3 = new javax.swing.JButton();
        lblBase = new javax.swing.JLabel();

        lblTablaConocimiento.setText("Tabla de conocimiento :");

        cmbBoxTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBoxTablasItemStateChanged(evt);
            }
        });

        jScrollPane1.setViewportView(lstAtributosPredictores);

        jScrollPane2.setViewportView(lstPrepareAtribPred);

        btnAgregarAtribPred.setText("Agregar");
        btnAgregarAtribPred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAtribPredActionPerformed(evt);
            }
        });

        btnEliminarAtribPred.setText("Eliminar");
        btnEliminarAtribPred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAtribPredActionPerformed(evt);
            }
        });

        btnAgregarBase.setText("Agregar Base");
        btnAgregarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBaseActionPerformed(evt);
            }
        });

        txtBase.setEditable(false);

        btnEliminarBase.setText("Eliminar Base");
        btnEliminarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBaseActionPerformed(evt);
            }
        });

        btnCalcularID3.setText("Calcular ID3");
        btnCalcularID3.setEnabled(false);
        btnCalcularID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularID3ActionPerformed(evt);
            }
        });

        lblBase.setText("Base:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTablaConocimiento)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarBase))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBase)
                                .addGap(273, 273, 273))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBase)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarAtribPred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarAtribPred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btnCalcularID3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTablaConocimiento)
                    .addComponent(cmbBoxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarAtribPred)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarAtribPred))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnCalcularID3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarBase)
                    .addComponent(lblBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarBase)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBoxTablasItemStateChanged
        String tabla = cmbBoxTablas.getSelectedItem().toString();
        lmAtribPred.removeAllElements();
        lmPrepareAtribPred.removeAllElements();
        txtBase.setText(null);
        btnCalcularID3.setEnabled(false);
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SHOW COLUMNS FROM " + tabla);
            while (rs.next()) {
                lmAtribPred.addElement(rs.getString("Field"));
            }
            lstAtributosPredictores.setModel(lmAtribPred);
        } catch (SQLException ex) {
            Logger.getLogger(PnlPrepareID3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbBoxTablasItemStateChanged

    private void btnAgregarAtribPredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAtribPredActionPerformed
        List atributos = lstAtributosPredictores.getSelectedValuesList();
        for (Object atrib : atributos) {
            lmAtribPred.removeElement(atrib);
            lmPrepareAtribPred.addElement(atrib.toString());
        }
        lstPrepareAtribPred.setModel(lmPrepareAtribPred);
        if (!txtBase.getText().isEmpty()) {
            btnCalcularID3.setEnabled(true);
        }
    }//GEN-LAST:event_btnAgregarAtribPredActionPerformed

    private void btnEliminarAtribPredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAtribPredActionPerformed
        List atributos = lstPrepareAtribPred.getSelectedValuesList();
        for (Object atrib : atributos) {
            lmPrepareAtribPred.removeElement(atrib);
            lmAtribPred.addElement(atrib.toString());
        }
        lstAtributosPredictores.setModel(lmAtribPred);
        if (lmPrepareAtribPred.isEmpty()) {
            btnCalcularID3.setEnabled(false);
        }
    }//GEN-LAST:event_btnEliminarAtribPredActionPerformed

    private void btnAgregarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBaseActionPerformed
        List atributos = lstAtributosPredictores.getSelectedValuesList();
        if (!atributos.isEmpty()) {
            if (txtBase.getText().isEmpty()) {
                lmAtribPred.removeElement(atributos.get(0));
                txtBase.setText(atributos.get(0).toString());
            } else {
                lmAtribPred.removeElement(atributos.get(0));
                lmAtribPred.addElement(txtBase.getText());
                txtBase.setText(atributos.get(0).toString());
            }
        }
        if (!lmPrepareAtribPred.isEmpty()) {
            btnCalcularID3.setEnabled(true);
        }

    }//GEN-LAST:event_btnAgregarBaseActionPerformed

    private void btnEliminarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBaseActionPerformed
        if (!txtBase.getText().isEmpty()) {
            lmAtribPred.addElement(txtBase.getText());
            txtBase.setText(null);
            btnCalcularID3.setEnabled(false);
        }
    }//GEN-LAST:event_btnEliminarBaseActionPerformed

    private void btnCalcularID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularID3ActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Object obj : lmPrepareAtribPred.toArray()) {
            sb.append(obj.toString()).append(",");
        }
        String resultado = id3.core.getid3(sb.toString(), this.txtBase.getText(), this.cmbBoxTablas.getSelectedItem().toString(), subname, usuario, password);
        System.out.println(resultado);
        //resultado = resultado.substring(26);
        //System.out.println(resultado);
        Arbol arbol = new Arbol();
        List<NodoAgregable> nodos = new ArrayList<>();
        while (!resultado.isEmpty()) {
            int a = resultado.indexOf("|");
            String cadena1 = resultado.substring(0, a);
            resultado = resultado.substring(a + 1);
            int b = resultado.indexOf("|");
            String cadena2 = resultado.substring(0, b);
            resultado = resultado.substring(b + 1);
            //NodoAgregable na = new NodoAgregable(cadena1, cadena2);
            //System.out.println(cadena1);
            //System.out.println(cadena2);
            nodos.add(new NodoAgregable(cadena1, Integer.valueOf(cadena2)));
        }
        //System.out.println(nodos);
        arbol.setNodos(nodos);
        FramePaintTree dibujarArbol = new FramePaintTree();
        PnlPaintTree pnl = new PnlPaintTree();
        pnl.arbol = arbol;
        dibujarArbol.arbol = arbol;
        dibujarArbol.setTitle("Arbol : " + this.cmbBoxTablas.getSelectedItem().toString().toUpperCase());
        dibujarArbol.setContentPane(pnl);
        dibujarArbol.setVisible(true);
        //System.out.println(arbol);
    }//GEN-LAST:event_btnCalcularID3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAtribPred;
    private javax.swing.JButton btnAgregarBase;
    private javax.swing.JButton btnCalcularID3;
    private javax.swing.JButton btnEliminarAtribPred;
    private javax.swing.JButton btnEliminarBase;
    private javax.swing.JComboBox cmbBoxTablas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblTablaConocimiento;
    private javax.swing.JList lstAtributosPredictores;
    private javax.swing.JList lstPrepareAtribPred;
    private javax.swing.JTextField txtBase;
    // End of variables declaration//GEN-END:variables
}
